// Created by iWeb 3.0.2 local-build-20150109

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,58),url:'Remote_Run_Control_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Remote_Run_Control_files/stroke_1.png'},{rect:new IWRect(1,-1,283,2),url:'Remote_Run_Control_files/stroke_2.png'},{rect:new IWRect(284,-1,2,2),url:'Remote_Run_Control_files/stroke_3.png'},{rect:new IWRect(284,1,2,58),url:'Remote_Run_Control_files/stroke_4.png'},{rect:new IWRect(284,59,2,2),url:'Remote_Run_Control_files/stroke_5.png'},{rect:new IWRect(1,59,283,2),url:'Remote_Run_Control_files/stroke_6.png'},{rect:new IWRect(-1,59,2,2),url:'Remote_Run_Control_files/stroke_7.png'}],new IWSize(285,60)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,58),url:'Remote_Run_Control_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Remote_Run_Control_files/stroke_17.png'},{rect:new IWRect(1,-1,127,2),url:'Remote_Run_Control_files/stroke_18.png'},{rect:new IWRect(128,-1,2,2),url:'Remote_Run_Control_files/stroke_19.png'},{rect:new IWRect(128,1,2,58),url:'Remote_Run_Control_files/stroke_20.png'},{rect:new IWRect(128,59,2,2),url:'Remote_Run_Control_files/stroke_21.png'},{rect:new IWRect(1,59,127,2),url:'Remote_Run_Control_files/stroke_22.png'},{rect:new IWRect(-1,59,2,2),url:'Remote_Run_Control_files/stroke_23.png'}],new IWSize(129,60)),shadow_1:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),stroke_0:new IWEmptyStroke(),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,58),url:'Remote_Run_Control_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Remote_Run_Control_files/stroke_9.png'},{rect:new IWRect(1,-1,204,2),url:'Remote_Run_Control_files/stroke_10.png'},{rect:new IWRect(205,-1,2,2),url:'Remote_Run_Control_files/stroke_11.png'},{rect:new IWRect(205,1,2,58),url:'Remote_Run_Control_files/stroke_12.png'},{rect:new IWRect(205,59,2,2),url:'Remote_Run_Control_files/stroke_13.png'},{rect:new IWRect(1,59,204,2),url:'Remote_Run_Control_files/stroke_14.png'},{rect:new IWRect(-1,59,2,2),url:'Remote_Run_Control_files/stroke_15.png'}],new IWSize(206,60))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Remote_Run_Control_files/Remote_Run_ControlMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
