// Created by iWeb 3.0.4 local-build-20180321

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),stroke_0:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,24),url:'Scripting_Ref_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Scripting_Ref_files/stroke_1.png'},{rect:new IWRect(1,-1,85,2),url:'Scripting_Ref_files/stroke_2.png'},{rect:new IWRect(86,-1,2,2),url:'Scripting_Ref_files/stroke_3.png'},{rect:new IWRect(86,1,2,24),url:'Scripting_Ref_files/stroke_4.png'},{rect:new IWRect(86,25,2,2),url:'Scripting_Ref_files/stroke_5.png'},{rect:new IWRect(1,25,85,2),url:'Scripting_Ref_files/stroke_6.png'},{rect:new IWRect(-1,25,2,2),url:'Scripting_Ref_files/stroke_7.png'}],new IWSize(87,26)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,41),url:'Scripting_Ref_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Scripting_Ref_files/stroke_9.png'},{rect:new IWRect(1,-1,117,2),url:'Scripting_Ref_files/stroke_10.png'},{rect:new IWRect(118,-1,2,2),url:'Scripting_Ref_files/stroke_11.png'},{rect:new IWRect(118,1,2,41),url:'Scripting_Ref_files/stroke_12.png'},{rect:new IWRect(118,42,2,2),url:'Scripting_Ref_files/stroke_13.png'},{rect:new IWRect(1,42,117,2),url:'Scripting_Ref_files/stroke_14.png'},{rect:new IWRect(-1,42,2,2),url:'Scripting_Ref_files/stroke_15.png'}],new IWSize(119,43)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,58),url:'Scripting_Ref_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Scripting_Ref_files/stroke_17.png'},{rect:new IWRect(1,-1,122,2),url:'Scripting_Ref_files/stroke_18.png'},{rect:new IWRect(123,-1,2,2),url:'Scripting_Ref_files/stroke_19.png'},{rect:new IWRect(123,1,2,58),url:'Scripting_Ref_files/stroke_20.png'},{rect:new IWRect(123,59,2,3),url:'Scripting_Ref_files/stroke_21.png'},{rect:new IWRect(1,59,122,3),url:'Scripting_Ref_files/stroke_22.png'},{rect:new IWRect(-1,59,2,3),url:'Scripting_Ref_files/stroke_23.png'}],new IWSize(124,60)),stroke_4:new IWStrokeParts([{rect:new IWRect(-1,1,2,58),url:'Scripting_Ref_files/stroke_24.png'},{rect:new IWRect(-1,-1,2,2),url:'Scripting_Ref_files/stroke_25.png'},{rect:new IWRect(1,-1,154,2),url:'Scripting_Ref_files/stroke_26.png'},{rect:new IWRect(155,-1,2,2),url:'Scripting_Ref_files/stroke_27.png'},{rect:new IWRect(155,1,2,58),url:'Scripting_Ref_files/stroke_28.png'},{rect:new IWRect(155,59,2,2),url:'Scripting_Ref_files/stroke_29.png'},{rect:new IWRect(1,59,154,2),url:'Scripting_Ref_files/stroke_30.png'},{rect:new IWRect(-1,59,2,2),url:'Scripting_Ref_files/stroke_31.png'}],new IWSize(156,60))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Scripting_Ref_files/Scripting_RefMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
