// Created by iWeb 3.0.2 local-build-20150109

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_1:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),stroke_0:new IWEmptyStroke(),shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,108),url:'Random_Pulser_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Random_Pulser_files/stroke_1.png'},{rect:new IWRect(1,-1,102,2),url:'Random_Pulser_files/stroke_2.png'},{rect:new IWRect(103,-1,2,2),url:'Random_Pulser_files/stroke_3.png'},{rect:new IWRect(103,1,2,108),url:'Random_Pulser_files/stroke_4.png'},{rect:new IWRect(103,109,2,3),url:'Random_Pulser_files/stroke_5.png'},{rect:new IWRect(1,109,102,3),url:'Random_Pulser_files/stroke_6.png'},{rect:new IWRect(-1,109,2,3),url:'Random_Pulser_files/stroke_7.png'}],new IWSize(104,110)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,58),url:'Random_Pulser_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Random_Pulser_files/stroke_9.png'},{rect:new IWRect(1,-1,150,2),url:'Random_Pulser_files/stroke_10.png'},{rect:new IWRect(151,-1,2,2),url:'Random_Pulser_files/stroke_11.png'},{rect:new IWRect(151,1,2,58),url:'Random_Pulser_files/stroke_12.png'},{rect:new IWRect(151,59,2,2),url:'Random_Pulser_files/stroke_13.png'},{rect:new IWRect(1,59,150,2),url:'Random_Pulser_files/stroke_14.png'},{rect:new IWRect(-1,59,2,2),url:'Random_Pulser_files/stroke_15.png'}],new IWSize(152,60)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,58),url:'Random_Pulser_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Random_Pulser_files/stroke_17.png'},{rect:new IWRect(1,-1,103,2),url:'Random_Pulser_files/stroke_18.png'},{rect:new IWRect(104,-1,2,2),url:'Random_Pulser_files/stroke_19.png'},{rect:new IWRect(104,1,2,58),url:'Random_Pulser_files/stroke_20.png'},{rect:new IWRect(104,59,2,2),url:'Random_Pulser_files/stroke_21.png'},{rect:new IWRect(1,59,103,2),url:'Random_Pulser_files/stroke_22.png'},{rect:new IWRect(-1,59,2,2),url:'Random_Pulser_files/stroke_23.png'}],new IWSize(105,60))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Random_Pulser_files/Random_PulserMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
