// Created by iWeb 3.0.2 local-build-20150109

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,74),url:'Archival_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Archival_files/stroke_17.png'},{rect:new IWRect(1,-1,220,2),url:'Archival_files/stroke_18.png'},{rect:new IWRect(221,-1,2,2),url:'Archival_files/stroke_19.png'},{rect:new IWRect(221,1,2,74),url:'Archival_files/stroke_20.png'},{rect:new IWRect(221,75,2,2),url:'Archival_files/stroke_21.png'},{rect:new IWRect(1,75,220,2),url:'Archival_files/stroke_22.png'},{rect:new IWRect(-1,75,2,2),url:'Archival_files/stroke_23.png'}],new IWSize(222,76)),stroke_0:new IWEmptyStroke(),stroke_4:new IWStrokeParts([{rect:new IWRect(-1,1,2,125),url:'Archival_files/stroke_24.png'},{rect:new IWRect(-1,-1,2,2),url:'Archival_files/stroke_25.png'},{rect:new IWRect(1,-1,249,2),url:'Archival_files/stroke_26.png'},{rect:new IWRect(250,-1,2,2),url:'Archival_files/stroke_27.png'},{rect:new IWRect(250,1,2,125),url:'Archival_files/stroke_28.png'},{rect:new IWRect(250,126,2,2),url:'Archival_files/stroke_29.png'},{rect:new IWRect(1,126,249,2),url:'Archival_files/stroke_30.png'},{rect:new IWRect(-1,126,2,2),url:'Archival_files/stroke_31.png'}],new IWSize(251,127)),stroke_5:new IWStrokeParts([{rect:new IWRect(-1,1,2,79),url:'Archival_files/stroke_32.png'},{rect:new IWRect(-1,-1,2,2),url:'Archival_files/stroke_33.png'},{rect:new IWRect(1,-1,249,2),url:'Archival_files/stroke_34.png'},{rect:new IWRect(250,-1,2,2),url:'Archival_files/stroke_35.png'},{rect:new IWRect(250,1,2,79),url:'Archival_files/stroke_36.png'},{rect:new IWRect(250,80,2,2),url:'Archival_files/stroke_37.png'},{rect:new IWRect(1,80,249,2),url:'Archival_files/stroke_38.png'},{rect:new IWRect(-1,80,2,2),url:'Archival_files/stroke_39.png'}],new IWSize(251,81)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,164),url:'Archival_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Archival_files/stroke_9.png'},{rect:new IWRect(1,-1,376,2),url:'Archival_files/stroke_10.png'},{rect:new IWRect(377,-1,2,2),url:'Archival_files/stroke_11.png'},{rect:new IWRect(377,1,2,164),url:'Archival_files/stroke_12.png'},{rect:new IWRect(377,165,2,2),url:'Archival_files/stroke_13.png'},{rect:new IWRect(1,165,376,2),url:'Archival_files/stroke_14.png'},{rect:new IWRect(-1,165,2,2),url:'Archival_files/stroke_15.png'}],new IWSize(378,166)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,58),url:'Archival_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Archival_files/stroke_1.png'},{rect:new IWRect(1,-1,247,2),url:'Archival_files/stroke_2.png'},{rect:new IWRect(248,-1,2,2),url:'Archival_files/stroke_3.png'},{rect:new IWRect(248,1,2,58),url:'Archival_files/stroke_4.png'},{rect:new IWRect(248,59,2,2),url:'Archival_files/stroke_5.png'},{rect:new IWRect(1,59,247,2),url:'Archival_files/stroke_6.png'},{rect:new IWRect(-1,59,2,2),url:'Archival_files/stroke_7.png'}],new IWSize(249,60))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Archival_files/ArchivalMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
