// Created by iWeb 3.0.4 local-build-20170214

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,58),url:'MPodC_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'MPodC_files/stroke_9.png'},{rect:new IWRect(1,-1,180,2),url:'MPodC_files/stroke_10.png'},{rect:new IWRect(181,-1,2,2),url:'MPodC_files/stroke_11.png'},{rect:new IWRect(181,1,2,58),url:'MPodC_files/stroke_12.png'},{rect:new IWRect(181,59,2,2),url:'MPodC_files/stroke_13.png'},{rect:new IWRect(1,59,180,2),url:'MPodC_files/stroke_14.png'},{rect:new IWRect(-1,59,2,2),url:'MPodC_files/stroke_15.png'}],new IWSize(182,60)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,58),url:'MPodC_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'MPodC_files/stroke_17.png'},{rect:new IWRect(1,-1,180,2),url:'MPodC_files/stroke_18.png'},{rect:new IWRect(181,-1,2,2),url:'MPodC_files/stroke_19.png'},{rect:new IWRect(181,1,2,58),url:'MPodC_files/stroke_20.png'},{rect:new IWRect(181,59,2,2),url:'MPodC_files/stroke_21.png'},{rect:new IWRect(1,59,180,2),url:'MPodC_files/stroke_22.png'},{rect:new IWRect(-1,59,2,2),url:'MPodC_files/stroke_23.png'}],new IWSize(182,60)),stroke_0:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,74),url:'MPodC_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'MPodC_files/stroke_1.png'},{rect:new IWRect(1,-1,177,2),url:'MPodC_files/stroke_2.png'},{rect:new IWRect(178,-1,2,2),url:'MPodC_files/stroke_3.png'},{rect:new IWRect(178,1,2,74),url:'MPodC_files/stroke_4.png'},{rect:new IWRect(178,75,2,2),url:'MPodC_files/stroke_5.png'},{rect:new IWRect(1,75,177,2),url:'MPodC_files/stroke_6.png'},{rect:new IWRect(-1,75,2,2),url:'MPodC_files/stroke_7.png'}],new IWSize(179,76)),shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('MPodC_files/MPodCMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
