// Created by iWeb 3.0.2 local-build-20150109

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke(),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,24),url:'Set-up_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Set-up_files/stroke_17.png'},{rect:new IWRect(1,-1,126,2),url:'Set-up_files/stroke_18.png'},{rect:new IWRect(127,-1,2,2),url:'Set-up_files/stroke_19.png'},{rect:new IWRect(127,1,2,24),url:'Set-up_files/stroke_20.png'},{rect:new IWRect(127,25,2,2),url:'Set-up_files/stroke_21.png'},{rect:new IWRect(1,25,126,2),url:'Set-up_files/stroke_22.png'},{rect:new IWRect(-1,25,2,2),url:'Set-up_files/stroke_23.png'}],new IWSize(128,26)),stroke_5:new IWStrokeParts([{rect:new IWRect(-1,1,2,24),url:'Set-up_files/stroke_32.png'},{rect:new IWRect(-1,-1,2,2),url:'Set-up_files/stroke_33.png'},{rect:new IWRect(1,-1,77,2),url:'Set-up_files/stroke_34.png'},{rect:new IWRect(78,-1,2,2),url:'Set-up_files/stroke_35.png'},{rect:new IWRect(78,1,2,24),url:'Set-up_files/stroke_36.png'},{rect:new IWRect(78,25,2,2),url:'Set-up_files/stroke_37.png'},{rect:new IWRect(1,25,77,2),url:'Set-up_files/stroke_38.png'},{rect:new IWRect(-1,25,2,2),url:'Set-up_files/stroke_39.png'}],new IWSize(79,26)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,24),url:'Set-up_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Set-up_files/stroke_9.png'},{rect:new IWRect(1,-1,79,2),url:'Set-up_files/stroke_10.png'},{rect:new IWRect(80,-1,2,2),url:'Set-up_files/stroke_11.png'},{rect:new IWRect(80,1,2,24),url:'Set-up_files/stroke_12.png'},{rect:new IWRect(80,25,2,2),url:'Set-up_files/stroke_13.png'},{rect:new IWRect(1,25,79,2),url:'Set-up_files/stroke_14.png'},{rect:new IWRect(-1,25,2,2),url:'Set-up_files/stroke_15.png'}],new IWSize(81,26)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,25),url:'Set-up_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Set-up_files/stroke_1.png'},{rect:new IWRect(1,-1,75,2),url:'Set-up_files/stroke_2.png'},{rect:new IWRect(76,-1,2,2),url:'Set-up_files/stroke_3.png'},{rect:new IWRect(76,1,2,25),url:'Set-up_files/stroke_4.png'},{rect:new IWRect(76,26,2,2),url:'Set-up_files/stroke_5.png'},{rect:new IWRect(1,26,75,2),url:'Set-up_files/stroke_6.png'},{rect:new IWRect(-1,26,2,2),url:'Set-up_files/stroke_7.png'}],new IWSize(77,27)),stroke_4:new IWStrokeParts([{rect:new IWRect(-1,1,2,24),url:'Set-up_files/stroke_24.png'},{rect:new IWRect(-1,-1,2,2),url:'Set-up_files/stroke_25.png'},{rect:new IWRect(1,-1,54,2),url:'Set-up_files/stroke_26.png'},{rect:new IWRect(55,-1,2,2),url:'Set-up_files/stroke_27.png'},{rect:new IWRect(55,1,2,24),url:'Set-up_files/stroke_28.png'},{rect:new IWRect(55,25,2,2),url:'Set-up_files/stroke_29.png'},{rect:new IWRect(1,25,54,2),url:'Set-up_files/stroke_30.png'},{rect:new IWRect(-1,25,2,2),url:'Set-up_files/stroke_31.png'}],new IWSize(56,26))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Set-up_files/Set-upMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
