// Created by iWeb 3.0.2 local-build-20150109

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,179),url:'mySQL_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'mySQL_files/stroke_1.png'},{rect:new IWRect(1,-1,251,2),url:'mySQL_files/stroke_2.png'},{rect:new IWRect(252,-1,2,2),url:'mySQL_files/stroke_3.png'},{rect:new IWRect(252,1,2,179),url:'mySQL_files/stroke_4.png'},{rect:new IWRect(252,180,2,2),url:'mySQL_files/stroke_5.png'},{rect:new IWRect(1,180,251,2),url:'mySQL_files/stroke_6.png'},{rect:new IWRect(-1,180,2,2),url:'mySQL_files/stroke_7.png'}],new IWSize(253,181)),stroke_4:new IWStrokeParts([{rect:new IWRect(-1,1,2,92),url:'mySQL_files/stroke_24.png'},{rect:new IWRect(-1,-1,2,2),url:'mySQL_files/stroke_25.png'},{rect:new IWRect(1,-1,286,2),url:'mySQL_files/stroke_26.png'},{rect:new IWRect(287,-1,2,2),url:'mySQL_files/stroke_27.png'},{rect:new IWRect(287,1,2,92),url:'mySQL_files/stroke_28.png'},{rect:new IWRect(287,93,2,2),url:'mySQL_files/stroke_29.png'},{rect:new IWRect(1,93,286,2),url:'mySQL_files/stroke_30.png'},{rect:new IWRect(-1,93,2,2),url:'mySQL_files/stroke_31.png'}],new IWSize(288,94)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,108),url:'mySQL_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'mySQL_files/stroke_9.png'},{rect:new IWRect(1,-1,235,2),url:'mySQL_files/stroke_10.png'},{rect:new IWRect(236,-1,2,2),url:'mySQL_files/stroke_11.png'},{rect:new IWRect(236,1,2,108),url:'mySQL_files/stroke_12.png'},{rect:new IWRect(236,109,2,2),url:'mySQL_files/stroke_13.png'},{rect:new IWRect(1,109,235,2),url:'mySQL_files/stroke_14.png'},{rect:new IWRect(-1,109,2,2),url:'mySQL_files/stroke_15.png'}],new IWSize(237,110)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,58),url:'mySQL_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'mySQL_files/stroke_17.png'},{rect:new IWRect(1,-1,252,2),url:'mySQL_files/stroke_18.png'},{rect:new IWRect(253,-1,2,2),url:'mySQL_files/stroke_19.png'},{rect:new IWRect(253,1,2,58),url:'mySQL_files/stroke_20.png'},{rect:new IWRect(253,59,2,2),url:'mySQL_files/stroke_21.png'},{rect:new IWRect(1,59,252,2),url:'mySQL_files/stroke_22.png'},{rect:new IWRect(-1,59,2,2),url:'mySQL_files/stroke_23.png'}],new IWSize(254,60))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('mySQL_files/mySQLMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
